import uuid
from django.db import migrations,models
from django.db.models import Q
class Migration(migrations.Migration):
    initial=True;dependencies=[('pregnancies','0001_initial')]
    operations=[
        migrations.CreateModel(name='WeightMeasurement',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('measured_at',models.DateTimeField(db_index=True)),('note',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('value_kg',models.DecimalField(decimal_places=2,max_digits=6)),('pregnancy',models.ForeignKey(on_delete=models.deletion.CASCADE,to='pregnancies.pregnancy'))],options={'ordering':['-measured_at']}),
        migrations.CreateModel(name='BloodPressureMeasurement',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('measured_at',models.DateTimeField(db_index=True)),('note',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('systolic',models.PositiveIntegerField()),('diastolic',models.PositiveIntegerField()),('pulse',models.PositiveIntegerField(blank=True,null=True)),('pregnancy',models.ForeignKey(on_delete=models.deletion.CASCADE,to='pregnancies.pregnancy'))],options={'ordering':['-measured_at']}),
        migrations.CreateModel(name='BloodGlucoseMeasurement',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('measured_at',models.DateTimeField(db_index=True)),('note',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('value',models.DecimalField(decimal_places=2,max_digits=7)),('measurement_type',models.CharField(choices=[('FASTING','Fasting'),('BEFORE_MEAL','Before meal'),('AFTER_MEAL','After meal'),('OTHER','Other')],db_index=True,max_length=20)),('pregnancy',models.ForeignKey(on_delete=models.deletion.CASCADE,to='pregnancies.pregnancy'))],options={'ordering':['-measured_at']}),
        migrations.CreateModel(name='SymptomEntry',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('symptom_type',models.CharField(choices=[('NAUSEA','Nausea'),('HEADACHE','Headache'),('BACK_PAIN','Back pain'),('FATIGUE','Fatigue'),('SWELLING','Swelling'),('HEARTBURN','Heartburn'),('LEG_CRAMPS','Leg cramps'),('SLEEP_CHANGES','Sleep changes'),('MOOD_CHANGES','Mood changes'),('FREQUENT_URINATION','Frequent urination'),('OTHER','Other')],db_index=True,max_length=30)),('severity',models.CharField(choices=[('MILD','Mild'),('MODERATE','Moderate'),('SEVERE','Severe')],db_index=True,max_length=12)),('note',models.TextField(blank=True)),('occurred_at',models.DateTimeField(db_index=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('pregnancy',models.ForeignKey(on_delete=models.deletion.CASCADE,to='pregnancies.pregnancy'))],options={'ordering':['-occurred_at']}),
        migrations.AddConstraint(model_name='weightmeasurement',constraint=models.CheckConstraint(condition=Q(value_kg__gt=0),name='weight_positive')),
        migrations.AddConstraint(model_name='bloodpressuremeasurement',constraint=models.CheckConstraint(condition=Q(systolic__gt=0)&Q(diastolic__gt=0),name='bp_positive')),
        migrations.AddConstraint(model_name='bloodglucosemeasurement',constraint=models.CheckConstraint(condition=Q(value__gt=0),name='glucose_positive')),
    ]
