import uuid
from django.db import migrations,models
import apps.records.models
class Migration(migrations.Migration):
    initial=True;dependencies=[('pregnancies','0001_initial')]
    operations=[
        migrations.CreateModel(name='PrenatalVisit',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('provider_name',models.CharField(max_length=160)),('provider_type',models.CharField(choices=[('DOCTOR','Doctor'),('MIDWIFE','Midwife'),('OTHER','Other')],max_length=12)),('clinic_name',models.CharField(blank=True,max_length=200)),('scheduled_at',models.DateTimeField(db_index=True)),('status',models.CharField(choices=[('UPCOMING','Upcoming'),('COMPLETED','Completed'),('CANCELLED','Cancelled')],db_index=True,max_length=12)),('notes',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('pregnancy',models.ForeignKey(on_delete=models.deletion.CASCADE,related_name='visits',to='pregnancies.pregnancy'))],options={'ordering':['-scheduled_at']}),
        migrations.CreateModel(name='LabRecord',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('title',models.CharField(max_length=200)),('performed_at',models.DateTimeField(db_index=True)),('status',models.CharField(choices=[('SCHEDULED','Scheduled'),('COMPLETED','Completed'),('CANCELLED','Cancelled')],db_index=True,max_length=12)),('result_summary',models.TextField(blank=True)),('notes',models.TextField(blank=True)),('attachment',models.FileField(blank=True,upload_to=apps.records.models.upload_to,validators=[apps.records.models.medical_file_validator])),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('pregnancy',models.ForeignKey(on_delete=models.deletion.CASCADE,related_name='labs',to='pregnancies.pregnancy'))],options={'ordering':['-performed_at']}),
        migrations.CreateModel(name='UltrasoundRecord',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('title',models.CharField(max_length=200)),('performed_at',models.DateTimeField(db_index=True)),('gestational_week',models.PositiveSmallIntegerField()),('center_name',models.CharField(blank=True,max_length=200)),('summary',models.TextField(blank=True)),('notes',models.TextField(blank=True)),('attachment',models.FileField(blank=True,upload_to=apps.records.models.upload_to,validators=[apps.records.models.medical_file_validator])),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('pregnancy',models.ForeignKey(on_delete=models.deletion.CASCADE,related_name='ultrasounds',to='pregnancies.pregnancy'))],options={'ordering':['-performed_at']}),
        migrations.CreateModel(name='Medication',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('name',models.CharField(max_length=160)),('dosage_text',models.CharField(blank=True,max_length=200)),('schedule_text',models.CharField(blank=True,max_length=200)),('start_date',models.DateField()),('end_date',models.DateField(blank=True,null=True)),('notes',models.TextField(blank=True)),('is_active',models.BooleanField(db_index=True,default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('pregnancy',models.ForeignKey(on_delete=models.deletion.CASCADE,related_name='medications',to='pregnancies.pregnancy'))],options={'ordering':['-is_active','name']}),
        migrations.CreateModel(name='VisitQuestion',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('question',models.TextField()),('is_answered',models.BooleanField(default=False)),('answer_note',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('visit',models.ForeignKey(on_delete=models.deletion.CASCADE,related_name='questions',to='records.prenatalvisit'))]),
        migrations.CreateModel(name='MedicationIntake',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('date',models.DateField()),('completed',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('medication',models.ForeignKey(on_delete=models.deletion.CASCADE,related_name='intakes',to='records.medication'))]),
        migrations.AddConstraint(model_name='medicationintake',constraint=models.UniqueConstraint(fields=('medication','date'),name='unique_medication_intake_date')),
    ]
